version: "3"

services:
  strapi:
    image: "strapi/strapi"
    environment:
      DATABASE_CLIENT: "mysql"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USERNAME: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - 1337:1337
    volumes:
      - "./strapi:/srv/app"
    depends_on:
      - database

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./db:/var/lib/mysql"
